project:
  type: website

website:
  title: "PINNs - Escuela 2025"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "PINN Intro"
        href: intro.ipynb
      - text: "Colab"
        href: colab.ipynb
      - text: "Hands-on"
        href: PINN_notebook.ipynb

format:
  html:
    toc: true
    number-sections: true

publish:
  method: gh-pages